### ISSUE TITLE
Does not generate anything 

### ISSUE THREAD

**Issue by moronicgeek** [yayoc/swagger-to-mock#18]
When running 
npx swagger-to-mock with a normal swagger.json 
nothing is outputted. 

I tested the open api 3 yml file too and nothing is generated either. 

Great idea wish i could get it to work :)

**Comment by yugandhar-pathi** [comment]
Same here.
I get below two lines printed.
But not sure where the files are created.

```
swagger-to-mock
Completed
```

**Comment by yayoc** [comment]
Hi, Thanks for reporting. 
Could you share your yml file if possible to reproduce the issue?

@moronicgeek @yugandhar-pathi

**Comment by porteusconf** [comment]
Here is ipify.yml file that generates no output file(s).
```
swagger: '2.0'
info:
  description: A Simple IP Address API
  title: ipify
  version: "1.1"
host: api.ipify.org
schemes:
  - https
basePath: /
paths:
  /:
    get:
      summary: Get client
      parameters:
        - in: query
          name: format
          type: string
          description: 'The format to return the response in, i.e. json.'
          default: json
      responses:
        '200':
          description: Success response
          schema:
            type: object
            properties:
              ip:
                type: string
                example: 88.68.10.107
```

**Comment by yayoc** [comment]
@porteusconf 
Hi, It seems that your file looks swagger ver2 and this CLI only supports ver3.
