### ISSUE TITLE
Doesn't handle file $ref

### ISSUE THREAD

**Issue by btkelly** [yayoc/swagger-to-mock#22]
As defined in the [OpenAPI spec](https://swagger.io/docs/specification/using-ref/) a `$ref` object can be a remote reference to a file on the local machine. With my spec that is broken into multiple files I don't get any example data generation for a non root spec file.

**Comment by yayoc** [comment]
That's true, Currently `swagger-to-mock` does not support the `$ref` spec. 
Once I have the time, I will work on this.
