### ISSUE TITLE
Needs output directory parameter

### ISSUE THREAD

**Issue by dskvr** [yayoc/swagger-to-mock#7]
Presently, just spits files out where executed, this makes `swagger-to-mock` unsuitable for any automation processes.

**Comment by yayoc** [comment]
Thank you for feedback, That makes sense. will work on this when I have time.

**Comment by yayoc** [comment]
Published [v0.1.9](https://github.com/yayoc/swagger-to-mock/releases/tag/v0.1.9) supports an output path option ( -d, --dir option ). I hope it will work for your automation process.
